name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build docker --platform linux/amd64 --tag $DOCKER_REPO:$(date +%s)
    - name: Login Docker hub
      run: docker login -u lennardend -p ${{ secrets.DOCKER_PAT }}
    - name: Push the Docker image
      run: docker push $DOCKER_REPO
