name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build docker --platform linux/amd64 --tag ${{ vars.DOCKER_REPO }}
    - name: Login Docker hub
      run: echo ${{ secrets.DOCKER_PAT }} | docker login --username $DOCKER_USERNAME --password-stdin 
    - name: Push the Docker image
      run: docker push ${{ vars.DOCKER_REPO }}
